@base-url = http://localhost:8080/api/food
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZWNpcGVzLUFQSSIsInN1YiI6ImFwcHVzZXIiLCJhcHBVc2VySWQiOjEsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImV4cCI6MTY4MDIwODYwNn0.7Im3f1LzqQzpADEkvNkPJg1wqdx9mgZDILBFyZvUnqI

###

// findAll
GET {{base-url}} HTTP/1.1

###


GET {{base-url}}/1 HTTP/1.1
Authorization: Bearer {{jwt}}
###
